### ISSUE TITLE
Bug Flexbox sur le chatbot typeform

### ISSUE THREAD

**Issue by NicolasHov** [3615passtech/3615passtech.github.io#1]
Problème d'alignement à régler
(ma première issue wèèè)

**Comment by yvan-sraka** [comment]
Quel est exactement le bug ?

![](https://screenshotscdn.firefoxusercontent.com/images/2b60efe3-640c-4a82-9aa3-3d7029acb664.jpg)

Je crois que les couleurs ne sont pas très lisibles :/

Tu veux pas plutôt faire un block en `position: fixed` en bas à droite de la page ? (comme Messenger dans l'interface de Facebook)
